import { EventInfo } from '@/types'

// sample calendar event list
export const TEST_EVENTS: EventInfo[] = [
    {
        id: 1,
        title: 'Long Event1111111111111111',
        start: new Date(),
        end: new Date(),
        allDay: true,
        index: 12,
        users: [
          {
            id: 1,
            name: 'Andy Huan',
            mail: 'andy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 2,
            name: 'Bendy Juan',
            mail: 'bendy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 3,
            name: 'Cindy Chen',
            mail: 'cindy@gmail.com',
            language: 'chinese',
            icon: '',
            timeZone: null,
          },
        ],
        eventType: {
          type: 'stay',
          name: 'Tokyo Hotel'
        },
        location: 'Tokyo Hotel xxxx',
        commute: null,
        googleMapUrl: null,
        images: [],
      },
      {
        id: 2,
        title: 'Long Event2',
        start: new Date(),
        end: new Date(),
        allDay: true,
        index: 234,
        users: [
          {
            id: 1,
            name: 'Andy Huan',
            mail: 'andy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 2,
            name: 'Bendy Juan',
            mail: 'bendy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 3,
            name: 'Cindy Chen',
            mail: 'cindy@gmail.com',
            language: 'chinese',
            icon: '',
            timeZone: null,
          },
        ],
        eventType: {
          type: 'stay',
          name: 'Tokyo Hotel'
        },
        location: 'Tokyo Hotel xxxx',
        commute: null,
        googleMapUrl: null,
        images: [],
      },
      {
        id: 3,
        title: 'Long Event2',
        start: new Date(),
        end: new Date(),
        allDay: true,
        index: 3,
        users: [
          {
            id: 1,
            name: 'Andy Huan',
            mail: 'andy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 2,
            name: 'Bendy Juan',
            mail: 'bendy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 3,
            name: 'Cindy Chen',
            mail: 'cindy@gmail.com',
            language: 'chinese',
            icon: '',
            timeZone: null,
          },
        ],
        eventType: {
          type: 'stay',
          name: 'Tokyo Hotel'
        },
        location: 'Tokyo Hotel xxxx',
        commute: null,
        googleMapUrl: null,
        images: [],
      },
      {
        id: 4,
        title: 'Long Event2',
        start: new Date(),
        end: new Date(),
        allDay: true,
        index: 0,
        users: [
          {
            id: 1,
            name: 'Andy Huan',
            mail: 'andy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 2,
            name: 'Bendy Juan',
            mail: 'bendy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 3,
            name: 'Cindy Chen',
            mail: 'cindy@gmail.com',
            language: 'chinese',
            icon: '',
            timeZone: null,
          },
        ],
        eventType: {
          type: 'stay',
          name: 'Tokyo Hotel'
        },
        location: 'Tokyo Hotel xxxx',
        commute: null,
        googleMapUrl: null,
        images: [],
      },
      {
        id: 5,
        title: 'Long Event2',
        start: new Date(),
        end: new Date(),
        allDay: true,
        index: 5,
        users: [
          {
            id: 1,
            name: 'Andy Huan',
            mail: 'andy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 2,
            name: 'Bendy Juan',
            mail: 'bendy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 3,
            name: 'Cindy Chen',
            mail: 'cindy@gmail.com',
            language: 'chinese',
            icon: '',
            timeZone: null,
          },
        ],
        eventType: {
          type: 'stay',
          name: 'Tokyo Hotel'
        },
        location: 'Tokyo Hotel xxxx',
        commute: null,
        googleMapUrl: null,
        images: [],
      },
      {
        id: 6,
        title: 'Long Event3',
        start: new Date('3 May 2024 00:00:00 +0900'), // UTCの2019/5/28 0時0分
        end: new Date('3 May 2024 4:00:00 +0900'),
        allDay: false,
        index: 6,
        users: [
          {
            id: 1,
            name: 'Andy Huan',
            mail: 'andy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 2,
            name: 'Bendy Juan',
            mail: 'bendy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 3,
            name: 'Cindy Chen',
            mail: 'cindy@gmail.com',
            language: 'chinese',
            icon: '',
            timeZone: null,
          },
        ],
        eventType: {
          type: 'stay',
          name: 'Tokyo Hotel'
        },
        location: 'Tokyo Hotel xxxx',
        commute: null,
        googleMapUrl: null,
        images: [],
      },
      {
        id: 65,
        title: 'Long Event3',
        start: new Date('3 May 2024 05:00:00 +0900'), // UTCの2019/5/28 0時0分
        end: new Date('3 May 2024 06:00:00 +0900'),
        allDay: false,
        index: 6,
        users: [
          {
            id: 1,
            name: 'Andy Huan',
            mail: 'andy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 2,
            name: 'Bendy Juan',
            mail: 'bendy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 3,
            name: 'Cindy Chen',
            mail: 'cindy@gmail.com',
            language: 'chinese',
            icon: '',
            timeZone: null,
          },
        ],
        eventType: {
          type: 'stay',
          name: 'Tokyo Hotel'
        },
        location: 'Tokyo Hotel xxxx',
        commute: null,
        googleMapUrl: null,
        images: [],
      },
      {
        id: 157,
        title: 'Long Event3',
        start: new Date('3 May 2024 07:00:00 +0900'), // UTCの2019/5/28 0時0分
        end: new Date('3 May 2024 10:00:00 +0900'),
        allDay: false,
        index: 6,
        users: [
          {
            id: 1,
            name: 'Andy Huan',
            mail: 'andy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 2,
            name: 'Bendy Juan',
            mail: 'bendy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 3,
            name: 'Cindy Chen',
            mail: 'cindy@gmail.com',
            language: 'chinese',
            icon: '',
            timeZone: null,
          },
        ],
        eventType: {
          type: 'stay',
          name: 'Tokyo Hotel'
        },
        location: 'Tokyo Hotel xxxx',
        commute: null,
        googleMapUrl: null,
        images: [],
      },
      {
        id: 0,
        title: 'Long Event3',
        start: new Date('3 May 2024 00:00:00 +0900'), // UTCの2019/5/28 0時0分
        end: new Date('3 May 2024 10:00:00 +0900'),
        allDay: false,
        index: 6,
        users: [
          {
            id: 1,
            name: 'Andy Huan',
            mail: 'andy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 2,
            name: 'Bendy Juan',
            mail: 'bendy@gmail.com',
            language: 'english',
            icon: '',
            timeZone: null,
          },
          {
            id: 3,
            name: 'Cindy Chen',
            mail: 'cindy@gmail.com',
            language: 'chinese',
            icon: '',
            timeZone: null,
          },
          {
            id: 4,
            name: 'Dandy Chen',
            mail: 'dandy@gmail.com',
            language: 'vietnam',
            icon: '',
            timeZone: null,
          },
        ],
        eventType: {
          type: 'stay',
          name: 'Tokyo Hotel'
        },
        location: 'Tokyo Hotel xxxx',
        commute: null,
        googleMapUrl: null,
        images: [],
      },
]