import { EventInfo, UserInfo } from '@/types'
import moment from 'moment'
import 'moment-timezone'

const userTimeZone = moment.tz.guess(true)
// sample calendar event list
export const TEST_EVENTS: EventInfo[] = [
  {
    id: 1,
    title: 'Long Event1111111111111111',
    start: new Date(),
    end: new Date(),
    allDay: true,
    index: 12,
    userIds: [1, 2, 3],
    eventType: {
      id: 1,
      title: 'Stay',
      icon: 'hotel',
      type: 'stay',
      color: '#39635E',
    },
    location: 'Tokyo Hotel xxxx',
    commute: null,
    googleMapUrl: null,
    images: [],
    timeZoneName: userTimeZone,
    description: '',
    mail: 'aaaa',
  },
  {
    id: 2,
    title: 'Long Event2',
    start: new Date(),
    end: new Date(),
    allDay: true,
    index: 234,
    userIds: [1, 2, 3],
    eventType: {
      id: 1,
      title: 'Stay',
      icon: 'hotel',
      type: 'stay',
      color: '#39635E',
    },
    location: 'Tokyo Hotel xxxx',
    commute: null,
    googleMapUrl: null,
    images: [],
    timeZoneName: userTimeZone,
    description: '',
    mail: 'aaaa',
  },
  {
    id: 3,
    title: 'Long Event2',
    start: new Date(),
    end: new Date(),
    allDay: true,
    index: 3,
    userIds: [1, 2, 3],
    eventType: {
      id: 1,
      title: 'Stay',
      icon: 'hotel',
      type: 'stay',
      color: '#39635E',
    },
    location: 'Tokyo Hotel xxxx',
    commute: null,
    googleMapUrl: null,
    images: [],
    timeZoneName: userTimeZone,
    description: '',
    mail: 'aaaa',
  },
  {
    id: 4,
    title: 'Long Event2',
    start: new Date(),
    end: new Date(),
    allDay: true,
    index: 0,
    userIds: [1, 2, 3],
    eventType: {
      id: 1,
      title: 'Stay',
      icon: 'hotel',
      type: 'stay',
      color: '#39635E',
    },
    location: 'Tokyo Hotel xxxx',
    commute: null,
    googleMapUrl: null,
    images: [],
    timeZoneName: userTimeZone,
    description: '',
    mail: 'aaaa',
  },
  {
    id: 5,
    title: 'Long Event2',
    start: new Date(),
    end: new Date(),
    allDay: true,
    index: 5,
    userIds: [1, 2, 3],
    eventType: {
      id: 1,
      title: 'Stay',
      icon: 'hotel',
      type: 'stay',
      color: '#39635E',
    },
    location: 'Tokyo Hotel xxxx',
    commute: null,
    googleMapUrl: null,
    images: [],
    timeZoneName: userTimeZone,
    description: '',
    mail: 'aaaa',
  },
  {
    id: 6,
    title: 'Long Event3',
    start: new Date('3 May 2024 00:00:00 +0900'), // UTCの2019/5/28 0時0分
    end: new Date('3 May 2024 4:00:00 +0900'),
    allDay: false,
    index: 6,
    userIds: [1, 2, 3],
    eventType: {
      id: 1,
      title: 'Stay',
      icon: 'hotel',
      type: 'stay',
      color: '#39635E',
    },
    location: 'Tokyo Hotel xxxx',
    commute: null,
    googleMapUrl: null,
    images: [],
    timeZoneName: userTimeZone,
    description: '',
    mail: 'aaaa',
  },
  {
    id: 65,
    title: 'Long Event3',
    start: new Date('3 May 2024 05:00:00 +0900'), // UTCの2019/5/28 0時0分
    end: new Date('3 May 2024 06:00:00 +0900'),
    allDay: false,
    index: 6,
    userIds: [1, 2, 3],
    eventType: {
      id: 1,
      title: 'Stay',
      icon: 'hotel',
      type: 'stay',
      color: '#39635E',
    },
    location: 'Tokyo Hotel xxxx',
    commute: null,
    googleMapUrl: null,
    images: [],
    timeZoneName: userTimeZone,
    description: '',
    mail: 'aaaa',
  },
  {
    id: 157,
    title: 'Long Event3',
    start: new Date('3 May 2024 07:00:00 +0900'), // UTCの2019/5/28 0時0分
    end: new Date('3 May 2024 10:00:00 +0900'),
    allDay: false,
    index: 6,
    userIds: [1, 2, 3],
    eventType: {
      id: 1,
      title: 'Stay',
      icon: 'hotel',
      type: 'stay',
      color: '#39635E',
    },
    location: 'Tokyo Hotel xxxx',
    commute: null,
    googleMapUrl: null,
    images: [],
    timeZoneName: userTimeZone,
    description: '',
    mail: 'aaaa',
  },
  {
    id: 0,
    title: 'Long Event3',
    start: new Date('3 May 2024 00:00:00 +0900'), // UTCの2019/5/28 0時0分
    end: new Date('3 May 2024 10:00:00 +0900'),
    allDay: false,
    index: 6,
    userIds: [1, 2, 3, 4],
    eventType: {
      id: 1,
      title: 'Stay',
      icon: 'hotel',
      type: 'stay',
      color: '#39635E',
    },
    location: 'Tokyo Hotel xxxx',
    commute: null,
    googleMapUrl: null,
    images: [],
    timeZoneName: userTimeZone,
    description: '',
    mail: 'aaaa',
  },
]

// all users list
export const All_USERS: UserInfo[] = [
  {
    id: 1,
    name: 'Andy Huan',
    mail: 'andy@gmail.com',
    language: 'Japanese',
    icon: 'https://caricom.org/wp-content/uploads/Floyd-Morris-Remake-1024x879-1.jpg',
    timeZoneName: 'Asia/Tokyo',
  },
  {
    id: 2,
    name: 'Bendy Chang',
    mail: 'bendy@gmail.com',
    language: 'Japanese',
    icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGkWQQUpfOefJn7Ut08BzrqSdBTYYa_nxxxFl43O9Dg&s',
    timeZoneName: 'Asia/Tokyo',
  },
  {
    id: 3,
    name: 'Jessica Smith',
    mail: 'jessi@gmail.com',
    language: 'Japanese',
    icon: 'https://images.healthshots.com/healthshots/en/uploads/2020/12/08182549/positive-person.jpg',
    timeZoneName: 'Asia/Tokyo',
  },
  {
    id: 4,
    name: 'Jake Jones',
    mail: 'jake@gmail.com',
    language: 'Japanese',
    icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRmilJls7TJF3iQZrqlRp9wyrKHckJQdv4NNvC0UY3eQ&s',
    timeZoneName: 'Asia/Tokyo',
  },
  {
    id: 5,
    name: 'Charlotte Roberts',
    mail: 'char@gmail.com',
    language: 'Japanese',
    icon: 'https://pbs.twimg.com/profile_images/1465102977312636929/oXKdq9aL_400x400.jpg',
    timeZoneName: 'Asia/Tokyo',
  },
  {
    id: 6,
    name: 'Elizabeth Brown',
    mail: 'eli@gmail.com',
    language: 'Japanese',
    icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCcEHMyxVut3HjBE-TuARsKgR5FoBspda8M8R6dtROPQ&s',
    timeZoneName: 'Asia/Tokyo',
  },
]